AWSTemplateFormatVersion: 2010-09-09
Description: Guidance for Custom Search of an Enterprise Knowledge Base on AWS - (SO9251)
Parameters:
  KendraIndexName:
    Type: String
    Description: The name of the Kendra index.
    Default: rag-kendra
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket.
    Default: rag-bucket
Resources:
  KendraRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - kendra.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: kendra-access-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutBucketPolicy'
                Resource: 
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
                Condition:
                  StringEquals:
                    'cloudwatch:namespace': AWS/Kendra
              - Effect: Allow
                Action:
                  - 'logs:DescribeLogGroups'
                  - 'logs:CreateLogGroup'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kendra/*'
              - Effect: Allow
                Action:
                  - 'logs:DescribeLogStreams'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kendra/*:log-stream:*'
  KendraIndex:
    Type: 'AWS::Kendra::Index'
    Properties:
      RoleArn: !GetAtt 
        - KendraRole
        - Arn
      Description: Kendra index for document search
      Name: !Ref KendraIndexName
      Edition: DEVELOPER_EDITION
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt 
                - KendraRole
                - Arn
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
  KendraDataSource:
    Type: 'AWS::Kendra::DataSource'
    Properties:
      IndexId: !Ref KendraIndex
      Name: KendraDataSource
      Type: S3
      RoleArn: !GetAtt 
        - KendraRole
        - Arn
      DataSourceConfiguration:
        S3Configuration:
          BucketName: !Ref S3Bucket
      Description: S3 Data source for Kendra
Outputs:
  KendraIndexURL:
    Description: The URL of the Kendra Index
    Value: !Sub 'https://console.aws.amazon.com/kendra/home?region=${AWS::Region}#indexes/details/${KendraIndex}'
  S3BucketURL:
    Description: The URL of the S3 Bucket
    Value: !Sub 'https://s3.console.aws.amazon.com/s3/buckets/${S3BucketName}'